### ISSUE TITLE
Annotation section sometimes doesn't render on variant page

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomad_browser#116]
example:

http://gnomad.broadinstitute.org/variant/11-94169012-T-TGAAGTGGTAGGAAAAATGTC

**Comment by bw2** [comment]
Missing annotation section:
![image](https://user-images.githubusercontent.com/6240170/39891468-abf2cea2-546b-11e8-9716-
11b58a89ff39.png)

should look like:
![image](https://user-images.githubusercontent.com/6240170/39891502-c380acb0-546b-11e8-87e5-a9bcbb12ab5f.png)
(example from http://gnomad.broadinstitute.org/variant/1-55516888-G-GA)

**Comment by nawatts** [comment]
For this particular variant (11-94169012-T-TGAAGTGGTAGGAAAAATGTC), the annotation section is empty because the `consequences` object is empty.

https://github.com/macarthur-lab/gnomad_browser/blob/9b970bf7629002d13961cf4fbcfbd679b7960eeb/templates/variant.html#L593-L600

It looks like the template assumes there will be consequence information if `variant.vep_annotations` is not empty. However, `variant` may be populated from either ExAC or gnomAD data, while `consequences` is always from `ExAC` data.

https://github.com/macarthur-lab/gnomad_browser/blob/9b970bf7629002d13961cf4fbcfbd679b7960eeb/exac.py#L778-L798

For 11-94169012-T-TGAAGTGGTAGGAAAAATGTC, `exac['consequences']` is empty but `gnomad['consequences']` is not.
