### ISSUE TITLE
In VCFs, consequences cannot be reliably mapped to alt alleles

### ISSUE THREAD

**Issue by pdl** [macarthur-lab/gnomad_browser#48]
The alt allele given as the first pipe-separated column of the CSQ field does not necessarily match the alt in the VCF column.

Consider the genomes entry:

    21 10910129 . CAAAT TAAAT,C,CAAT

There are multiple annotations for the same transcript with alt allele of `-`, i.e. the two deletions are annotated separately; the `T` (C/T, i.e. CAAAT/TAAAT) is also annotated. I suspect the VEP call preceded the operation which normalised the variants.

The only possible way of correctly mapping these as far as I can see is to parse the HGVS code, turn it into genomic coordinates, normalise it AND the original variant (because of #47) and then try to match them up. This would be extremely impractical to do at scale.

**Comment by carbocation** [comment]
A simple example of this comes from the following entry:
```
1	139015	rs545682419	G	T,A,GT	87423.15	PASS
```
Due to the way that [ensembl alt variants get translated from VCF variants](http://www.ensembl.org/info/docs/tools/vep/vep_formats.html), there is ambiguity in the output:

There are two SNVs: G-->T and G-->A

There is also an indel: G-->GT (insertion of a T)

Due to the way the CSQ field is annotated, both the G-->T SNV and the G-->GT indel are annotated as "T" in the CSQ field:

```
CSQ=T|frameshift_variant|HIGH|AL627309.1
```

```
,T|missense_variant|MODERATE|AL627309.1
```

As far as I can tell, based on the current annotation approach, there is insufficient information here to unambiguously handle this data (aside from parsing that the frameshift must be referring to G-->GT, etc).

**Comment by mattsolo1** [comment]
You can use the ALLELE_NUM field to map alt alleles to annotations. For example,  see `parsing.py` to see how this is handled in the browser:

https://github.com/macarthur-lab/gnomad_browser/blob/master/parsing.py#L113

```
consequence_array = info_field['CSQ'].split(',') if 'CSQ' in info_field else []
annotations = [dict(zip(vep_field_names, x.split('|'))) for x in consequence_array if len(vep_field_names) == len(x.split('|'))]

alt_alleles = fields[4].split(',')
for i, alt_allele in enumerate(alt_alleles):
    if alt_allele == "*":
        continue

    vep_annotations = [ann for ann in coding_annotations if int(ann['ALLELE_NUM']) == i + 1]
	...etc
```

**Comment by pdl** [comment]
Thanks, this seems to work.
