### ISSUE TITLE
abeaudetbcm

### ISSUE THREAD

**Issue by abeaudetbcm** [macarthur-lab/gnomad_browser#50]
All the SNP data on X are messed up because it show the allele number as 2x the individual number.  If it is half male and half female, the allele number should be 1.5x the individual number. See example below.  Clue: Males have 1 X and females have 2!!
Art Beaudet

rs5940487
Variant: X:154778278 C / T

Warning! This variant is only covered in 9989 individuals (adjusted allele number = 19978).
 This means that the site is covered in fewer than 80% of the individuals in ExAC, which may indicate a low-quality site.

**Comment by konradjk** [comment]
Aha! Good catch, though it's not as bad as it may seem: the allele number is actually correctly calculated as males+2*females (note there are a couple of odd-numbered allele numbers in the frequency table down the page). However, the "number of individuals" in the warning above is wrong (appears to be just allele number divided by 2), so that definitely needs fixing.

**Comment by konradjk** [comment]
@mattsolo1 the relevant line is https://github.com/macarthur-lab/gnomad_browser/blob/cb5e584ddc7a6b36758a3ca1fa1833543d329d39/templates/variant.html#L420 - this should be fixed to something like `AN_Male + AN_Female` if we load those in for all variants. If not, we'll have to 1) keep it as is for autosomes, 2) `AN_Male + AN_Female` for X, and 3) `AN_Male` for Y

**Comment by nawatts** [comment]
This message has since been removed from the gnomAD browser.

https://github.com/macarthur-lab/gnomad_browser/blob/453a7e4b0162abadb5877806d0f4aae4383a2496/templates/variant.html#L428-L431
